language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
before_script:
- npm install -g yarn
- yarn global add gulp-cli node-gyp gulp
install:
- yarn install
script:
- gulp lint
- gulp stylint
- gulp build